### ISSUE TITLE
Todo’s

### ISSUE THREAD

**Issue by JordyHers** [JordyHers/jordyhers#1]
https://youtu.be/OMSV-fDUgC4

- [x] SelectableText
- [x] Mouse Region 
- [x] LinkedIn-GitHub-Portfolio-Resume
- [x] Use urlLauncher
- [x] Navigation 2.0 / GetX
- [x] AnchorElement (download Portfolio)
- [x] Firestore save email 
- [x] About Page 
- [x] Test Responsive widgets
- [x] Buy domain
- [x] Publish website.
